config/routes.rb
# Rails.application.routes.draw do
  # devise_for :users
#     get 'welcome/home'
#     get 'welcome/app'
    # namespace :api, defaults: {format: :json} do

    # resources :users, only: [:create, :show]
    # resources :routes, only: [:index, :show, :create, :destroy]
    # resources :workouts, only: [:show, :create, :index, :destroy, :update]
    # resource :session, only: [:create, :destroy, :show]

  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    # root 'welcome#home'
# end

Rails.application.routes.draw do
  devise_for :users
  get 'welcome/home'
  get '/app', to: 'welcome#app', as: 'app'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,  :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/confirmations_controller.rb
class Devise::ConfirmationsController < DeviseController
    # GET /resource/confirmation/new
    def new
      self.resource = resource_class.new
    end
  
    # POST /resource/confirmation
    def create
      self.resource = resource_class.send_confirmation_instructions(resource_params)
      yield resource if block_given?
  
      if successfully_sent?(resource)
        respond_with({}, location: after_resending_confirmation_instructions_path_for(resource_name))
      else
        respond_with(resource)
      end
    end
  
    # GET /resource/confirmation?confirmation_token=abcdef
    def show
      self.resource = resource_class.confirm_by_token(params[:confirmation_token])
      yield resource if block_given?
  
      if resource.errors.empty?
        set_flash_message!(:notice, :confirmed)
        respond_with_navigational(resource){ redirect_to after_confirmation_path_for(resource_name, resource) }
      else
        respond_with_navigational(resource.errors, status: :unprocessable_entity){ render :new }
      end
    end
  
    protected
  
      # The path used after resending confirmation instructions.
      def after_resending_confirmation_instructions_path_for(resource_name)
        is_navigational_format? ? new_session_path(resource_name) : '/'
      end
  
      # The path used after confirmation.
      def after_confirmation_path_for(resource_name, resource)
        if signed_in?(resource_name)
          signed_in_root_path(resource)
        else
          new_session_path(resource_name)
        end
      end
  
      def translation_scope
        'devise.confirmations'
      end
  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def app
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandbagger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/welcome/app.html.erb
<div id="root"></div>
<%= javascript_pack_tag 'index' %>

app/views/welcome/home.html.erb
<nav style="text-align: right">
<% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>          
  <% else %>
    <%= link_to('Login', new_user_session_path)  %> |
    <%= link_to('Sign Up', new_user_registration_path)  %>  
  <% end %>
</nav>
<h1 class='welcome'>Welcome#home</h1>
<p>If you're logged in, check out 
<% if user_signed_in? %>
  <%= link_to "the app", app_path %>
<% else %>
  <%= link_to('the app', new_user_registration_path)  %> 
<% end %>!</p>



<!-- 
<h1>Hello, Rails!</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %> 
-->